"""
Django settings for FinSyncBackend project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decimal import Decimal
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y%_^=2w=a52x7yvsko*o9%r%i=4w7t=_%w658fzr2z!)w8i)&e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS from .env, split by comma if multiple are provided
allowed_hosts_str = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()] 
if '*' in ALLOWED_HOSTS: # Handle wildcard properly
    ALLOWED_HOSTS = ['*']


# Application definition

SYSTEM_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites'
]
THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',  # Added for CORS handling
]

USER_DEFINED_APPS = [
    'FinSyncAuth',
    'FinSyncOrganizations',
    'FinSyncIntegrations'
]

INSTALLED_APPS = USER_DEFINED_APPS + SYSTEM_APPS + THIRD_PARTY_APPS 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # CORS Middleware, place high
    'FinSyncIntegrations.middleware.OAuthSessionMiddleware',  # Add our OAuth session middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware', 
]

# CORS Settings from .env
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False').lower() == 'true'

print(CORS_ALLOW_ALL_ORIGINS)

# If not allowing all, you would parse CORS_ALLOWED_ORIGINS from .env (e.g., as a comma-separated string)
# CORS_ALLOWED_ORIGINS_STR = os.getenv('CORS_ALLOWED_ORIGINS', '')
# CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_STR.split(',') if origin.strip()]
# Ensure CORS_ALLOW_CREDENTIALS = True if you need to send cookies/auth headers from different origins
CORS_ALLOW_CREDENTIALS = True # Often needed for token-based auth


ROOT_URLCONF = 'FinSyncBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# --- Django REST Framework Settings ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Use JWT authentication globally
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # SessionAuth might be useful for browsable API / traditional login
        # 'rest_framework.authentication.SessionAuthentication', 
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    )
}

# --- dj-rest-auth & simplejwt Settings ---
REST_AUTH = {
    'USE_JWT': True, # Tell dj-rest-auth to use JWT
    'JWT_AUTH_HTTPONLY': False, # Allow JWT tokens to be accessed by JS
                                # Set to True if using HttpOnly cookies for refresh token
    'JWT_AUTH_COOKIE': None, # Don't send auth token in cookie (we'll use Authorization header)
    'JWT_AUTH_REFRESH_COOKIE': None, # Set cookie name if using HttpOnly refresh tokens
    # 'USER_DETAILS_SERIALIZER': 'FinSyncAuth.serializers.UserDetailsSerializer', # Optional: Custom user details
    'REGISTER_SERIALIZER': 'FinSyncAuth.serializers.CustomRegisterSerializer', 
     'SESSION_LOGIN': False, # Disable session login as we use JWT
}

# --- simplejwt Settings ---
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', '60'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': os.getenv('JWT_ROTATE_REFRESH_TOKENS', 'True').lower() == 'true',
    # 'BLACKLIST_AFTER_ROTATION': True, # Consider this based on your security needs
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY, # Uses the SECRET_KEY loaded from .env or default
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',
}



WSGI_APPLICATION = 'FinSyncBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3', # SQLite in project root if DEBUG is True
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'), # e.g., localhost or a DB server address
            'PORT': os.getenv('DB_PORT', '5432'), # Default PostgreSQL port
        }
    }
    # Optional: Add a check here to ensure all required DB env vars are set if not DEBUG
    if not all([DATABASES['default']['NAME'], DATABASES['default']['USER'], DATABASES['default']['PASSWORD'], DATABASES['default']['HOST']]):
        raise ImproperlyConfigured("Production database settings (DB_NAME, DB_USER, DB_PASSWORD, DB_HOST) must be set in .env when DEBUG is False.")


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- django-allauth Settings ---
AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1 # Required by django.contrib.sites

# ACCOUNT_AUTHENTICATION_METHOD = 'email' # Use email for login
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_LOGIN_METHODS = ['email']
ACCOUNT_SIGNUP_FIELDS = ['first_name*', 'last_name*', 'email*', 'password1*', 'password2*']  
ACCOUNT_EMAIL_VERIFICATION = 'mandatory' # Or 'optional' or 'none'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True # Allow clicking link to confirm
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_GET = True # Logout via GET request to logout URL
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_LOGOUT_REDIRECT_URL = '/api/auth/login/' # Or frontend URL
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_PRESERVE_USERNAME_CASING = False
ACCOUNT_SESSION_REMEMBER = None # Control "remember me" behavior
# ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True # Make users confirm password
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_ADAPTER = 'FinSyncAuth.adapter.CustomAccountAdapter' # We'll create this for company domain login




# --- Social Account Settings (Google) ---
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True, # Recommended for security
        # Get these from Google Cloud Console -> APIs & Services -> Credentials
        'APP': {
            'client_id': 'YOUR_GOOGLE_CLIENT_ID',
            'secret': 'YOUR_GOOGLE_CLIENT_SECRET',
            'key': '' # Usually not needed for OAuth2
        }
    }
}
SOCIALACCOUNT_ADAPTER = 'FinSyncAuth.adapter.CustomSocialAccountAdapter' # We'll create this too


# --- Email Configuration (for password reset, verification) ---
# Configure according to your email provider (e.g., SendGrid, Mailgun, Gmail for testing)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # For testing: prints emails to console
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your_email@example.com'
# EMAIL_HOST_PASSWORD = 'your_email_password'
# DEFAULT_FROM_EMAIL = 'noreply@yourdomain.com'


# --- Custom User Model ---
AUTH_USER_MODEL = 'FinSyncAuth.CustomUser'

ADMIN_ORG_NAME = os.getenv('ADMIN_ORG_NAME', 'SuperAdmin Organization')

# Custom Application Settings from .env
DEFAULT_TRIAL_DURATION_DAYS = int(os.getenv('DEFAULT_TRIAL_DURATION_DAYS', '14'))
DEFAULT_INVITE_EXPIRY_DAYS = int(os.getenv('DEFAULT_INVITE_EXPIRY_DAYS', '7'))

# Zoho and Frontend Redirect URL settings from .env
ZOHO_CLIENT_ID = os.getenv('ZOHO_CLIENT_ID')
ZOHO_CLIENT_SECRET = os.getenv('ZOHO_CLIENT_SECRET')
ZOHO_REDIRECT_URI = os.getenv('ZOHO_REDIRECT_URI')
ZOHO_AUTHORIZATION_URL = os.getenv('ZOHO_AUTHORIZATION_URL')
ZOHO_TOKEN_URL = os.getenv('ZOHO_TOKEN_URL')
ZOHO_SCOPES = os.getenv('ZOHO_SCOPES')
ZOHO_API_BASE_URL = os.getenv('ZOHO_API_BASE_URL')

FRONTEND_INTEGRATION_SUCCESS_URL = os.getenv('FRONTEND_INTEGRATION_SUCCESS_URL')
FRONTEND_INTEGRATION_FAILURE_URL = os.getenv('FRONTEND_INTEGRATION_FAILURE_URL')
FRONTEND_INTEGRATION_PENDING_CONFIG_URL = os.getenv('FRONTEND_INTEGRATION_PENDING_CONFIG_URL')

# Logging Configuration - Basic example, you might want to expand this
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO', # Or DEBUG if you want more verbose output
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        # You can add file handlers here if needed
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO', # Root logger level
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'FinSyncIntegrations': { # Example for one of your apps
            'handlers': ['console'],
            'level': 'DEBUG', # More detailed logging for your app during development
            'propagate': False,
        },
    }
}

# --- Session Settings ---
SESSION_COOKIE_AGE = 86400  # Session expiry in seconds (24 hours)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Keep sessions across browser close
SESSION_COOKIE_SECURE = False  # Set to True in HTTPS environments
SESSION_COOKIE_HTTPONLY = False  # Allow JavaScript to access session cookie for OAuth
SESSION_COOKIE_SAMESITE = None  # Allow cross-site cookies for OAuth redirects
SESSION_SAVE_EVERY_REQUEST = True  # Keep the session alive on every request
