# Generated by Django 5.0.1 on 2025-05-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('name', models.CharField(choices=[('trial', 'Trial'), ('individual', 'Individual'), ('team', 'Team')], help_text='Internal identifier for the plan (trial, individual, team).', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(help_text="User-facing name for the plan (e.g., 'Individual Plan', 'Team Plan (5 Users)').", max_length=100)),
                ('max_users', models.PositiveIntegerField(default=1, help_text='Maximum number of active users allowed within an Organization on this plan.')),
                ('max_integrations', models.PositiveIntegerField(default=1, help_text='Maximum number of active integrations (of any type) allowed for an Organization on this plan.')),
                ('is_trial', models.BooleanField(db_index=True, default=False, help_text='Designates this as the default trial plan assigned on initial organization creation.')),
                ('trial_duration_days', models.PositiveIntegerField(blank=True, default=14, help_text='Duration of the trial in days (only relevant if is_trial=True).', null=True)),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_annually', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('features', models.JSONField(blank=True, default=dict, help_text='List or dict of features included.')),
                ('is_available', models.BooleanField(default=True, help_text='Can users/organizations select this plan directly (e.g., during upgrade)? Trial plan should be False.')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the organization or workspace.', max_length=255)),
                ('domain', models.CharField(blank=True, db_index=True, help_text='Primary email domain associated with this organization, if applicable.', max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='General status flag for the organization account itself.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('inactive', 'Inactive')], default='trialing', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='Timestamp when the current trial period expires.', null=True)),
                ('subscription_start_date', models.DateField(blank=True, help_text='Date the current paid subscription period started.', null=True)),
                ('subscription_end_date', models.DateField(blank=True, help_text='Date the current subscription period ends (due to cancellation).', null=True)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='FinSyncOrganizations.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
