# Generated by Django 5.0.1 on 2025-05-11 21:49

import FinSyncOrganizations.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinSyncOrganizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='User who originally created this organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Current administrative owner of this organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, default=FinSyncOrganizations.models.default_invite_code, help_text='Unique invite code.', max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='If set, this invite is specifically for this email address.', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this invite code can still be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, default=FinSyncOrganizations.models.default_invite_expiry, help_text='When this invite code expires. Null means it never expires.', null=True)),
                ('created_by', models.ForeignKey(help_text='The user who created this invite.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this invite belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='FinSyncOrganizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Invite',
                'verbose_name_plural': 'Organization Invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembershipLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('joined_signup', 'Joined via Signup'), ('joined_invite', 'Joined via Invite'), ('left_org', 'Left Organization'), ('removed_admin', 'Removed by Admin')], help_text='The type of membership action that occurred.', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who initiated the action (e.g., admin who removed member, or user who invited). Null if self-initiated or system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_org_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_logs', to='FinSyncOrganizations.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Membership Log',
                'verbose_name_plural': 'Organization Membership Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
