# Generated by Django 5.0.1 on 2025-06-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinSyncOrganizations', '0004_alter_organization_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price_annually',
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='Email for billing notifications (defaults to owner email)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_name',
            field=models.CharField(blank=True, help_text='Name for billing purposes', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_phone',
            field=models.CharField(blank=True, help_text='Phone number for billing', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='grace_period_ends_at',
            field=models.DateTimeField(blank=True, help_text='Grace period end for failed payments', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_payment_failed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last payment failure', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_failed_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive payment failures'),
        ),
        migrations.AddField(
            model_name='organization',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='INR', help_text='Currency code', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly price in INR', max_digits=8, null=True),
        ),
    ]
