# Generated by Django 5.0.1 on 2025-11-14 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FinSyncOrganizations', '0005_remove_subscriptionplan_price_annually_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_model', models.CharField(choices=[('gpt-4o', 'GPT-4 Omni'), ('gpt-4o-mini', 'GPT-4 Omni Mini'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku')], default='gpt-4o-mini', max_length=50)),
                ('temperature', models.FloatField(default=0.1, help_text='Temperature setting for the LLM (0.0-2.0)')),
                ('max_tokens', models.PositiveIntegerField(default=4096, help_text='Maximum tokens for LLM responses')),
                ('enable_multi_tool_calls', models.BooleanField(default=True, help_text='Allow the AI to make multiple tool calls per response')),
                ('auto_generate_summaries', models.BooleanField(default=True, help_text='Automatically generate conversation summaries')),
                ('daily_message_limit', models.PositiveIntegerField(default=100, help_text='Daily message limit per organization')),
                ('daily_tool_call_limit', models.PositiveIntegerField(default=500, help_text='Daily tool call limit per organization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to='FinSyncOrganizations.organization')),
            ],
            options={
                'verbose_name': 'Chat Settings',
                'verbose_name_plural': 'Chat Settings',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Auto-generated or user-set conversation title', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this conversation is active or archived')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='FinSyncOrganizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_text', models.TextField(help_text='AI-generated summary of the conversation')),
                ('key_insights', models.JSONField(default=list, help_text='List of key insights from the conversation')),
                ('financial_metrics_discussed', models.JSONField(default=list, help_text='List of financial metrics discussed')),
                ('tools_used', models.JSONField(default=list, help_text='List of tools used in this conversation')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='FinSyncChat.conversation')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField(help_text='The message content')),
                ('tool_calls', models.JSONField(blank=True, help_text='Tool calls made by the assistant (if role=assistant)', null=True)),
                ('tool_call_id', models.CharField(blank=True, help_text='ID of the tool call this message responds to (if role=tool)', max_length=255, null=True)),
                ('name', models.CharField(blank=True, help_text='Tool name (if role=tool)', max_length=255, null=True)),
                ('sequence_number', models.PositiveIntegerField(help_text='Order of message in conversation')),
                ('token_count', models.PositiveIntegerField(blank=True, help_text='Estimated token count for this message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='FinSyncChat.conversation')),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=255)),
                ('arguments', models.JSONField(help_text='Arguments passed to the tool')),
                ('result', models.JSONField(blank=True, help_text='Result returned by the tool', null=True)),
                ('execution_time', models.FloatField(help_text='Time taken to execute the tool in seconds')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed', null=True)),
                ('mcp_server_url', models.URLField(blank=True, help_text='URL of the MCP server that handled this tool call', null=True)),
                ('integration_id', models.UUIDField(blank=True, help_text='ID of the integration used for this tool call', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='FinSyncChat.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('tool_calls_made', models.PositiveIntegerField(default=0)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0, help_text='Estimated cost in USD', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_usage', to='FinSyncOrganizations.organization')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization', 'user', '-updated_at'], name='FinSyncChat_organiz_016796_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_active', '-updated_at'], name='FinSyncChat_is_acti_7de353_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sequence_number'], name='FinSyncChat_convers_31ade7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role', 'created_at'], name='FinSyncChat_role_17b873_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('conversation', 'sequence_number')},
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['tool_name', 'status', '-created_at'], name='FinSyncChat_tool_na_78de8c_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['message', 'created_at'], name='FinSyncChat_message_f147be_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['status', '-created_at'], name='FinSyncChat_status_47962c_idx'),
        ),
        migrations.AddIndex(
            model_name='usagetracking',
            index=models.Index(fields=['organization', 'date'], name='FinSyncChat_organiz_43cf77_idx'),
        ),
        migrations.AddIndex(
            model_name='usagetracking',
            index=models.Index(fields=['date'], name='FinSyncChat_date_410754_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagetracking',
            unique_together={('organization', 'date')},
        ),
    ]
