# Generated by Django 5.0.1 on 2025-11-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinSyncChat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsettings',
            name='preferred_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4 Omni'), ('gpt-4o-mini', 'GPT-4 Omni Mini'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku'), ('openrouter/moonshotai/kimi-k2', 'Kimi K2 (OpenRouter)')], default='openrouter/moonshotai/kimi-k2', max_length=50),
        ),
    ]
