# Generated by Django 5.0.1 on 2025-11-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinSyncChat', '0003_message_visualizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsettings',
            name='preferred_model',
            field=models.CharField(choices=[('openrouter/moonshotai/kimi-k2', 'Kimi K2 (OpenRouter)')], default='openrouter/moonshotai/kimi-k2', max_length=50),
        ),
    ]
