# Generated by Django 5.0.1 on 2025-11-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinSyncChat', '0004_alter_chatsettings_preferred_model'),
        ('FinSyncChat', '0004_message_sources'),
    ]

    operations = [
    ]
