# Generated by Django 5.0.1 on 2025-05-07 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FinSyncOrganizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('zohobooks', 'Zoho Books'), ('quickbooks', 'QuickBooks Online')], db_index=True, max_length=50)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Identifier from the external provider (e.g., RealmID, OrgID). Required for most integrations.', max_length=255, null=True)),
                ('name', models.CharField(blank=True, help_text="User-defined name for this connection (e.g., 'Main Zoho Account', 'US QB Company').", max_length=100, null=True)),
                ('connection_status', models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected'), ('NeedsReauth', 'Needs Reauthorization'), ('Error', 'Error')], default='Disconnected', max_length=20)),
                ('access_token_encrypted', models.TextField(blank=True, help_text='Encrypted access token', null=True)),
                ('refresh_token_encrypted', models.TextField(blank=True, help_text='Encrypted refresh token', null=True)),
                ('token_expiry', models.DateTimeField(blank=True, help_text='Approximate expiry time of the access token', null=True)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by_user', models.ForeignKey(blank=True, help_text='The user who originally established this connection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_integrations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='FinSyncOrganizations.organization')),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'ordering': ['organization__name', 'provider', 'created_at'],
                'unique_together': {('organization', 'provider', 'external_id')},
            },
        ),
    ]
