# Generated by Django 5.0.1 on 2025-06-10 23:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinSyncIntegrations', '0001_initial'),
        ('FinSyncOrganizations', '0004_alter_organization_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='connection_status',
            field=models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected'), ('NeedsReauth', 'Needs Reauthorization'), ('Error', 'Error'), ('PendingExternalID', 'Pending External ID Selection')], default='Disconnected', max_length=30),
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(db_index=True, max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('zohobooks', 'Zoho Books'), ('quickbooks', 'QuickBooks Online')], help_text='The integration provider this state is for', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific data needed during OAuth flow')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to='FinSyncOrganizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth State',
                'verbose_name_plural': 'OAuth States',
                'indexes': [models.Index(fields=['created_at'], name='FinSyncInte_created_090e1a_idx'), models.Index(fields=['expires_at'], name='FinSyncInte_expires_6ae0db_idx'), models.Index(fields=['provider', 'created_at'], name='FinSyncInte_provide_4e159e_idx')],
            },
        ),
    ]
